FROM mcr.microsoft.com/dotnet/sdk:9.0

WORKDIR /src

COPY ["ecommerce-backend.csproj", "./"]
RUN dotnet restore "ecommerce-backend.csproj"

COPY . .

RUN dotnet tool install --global dotnet-ef
ENV PATH="${PATH}:/root/.dotnet/tools"

RUN dotnet publish "ecommerce-backend.csproj" -c Release -o /app/publish
COPY ./csv /app/publish/csv
WORKDIR /app/publish

COPY entrypoint.sh .
RUN chmod +x entrypoint.sh

EXPOSE 5000
ENTRYPOINT ["./entrypoint.sh"]
